version: "3.8"
services:
  mongodb:
    image: mongo:6
    container_name: cfh_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=crochetfromheart

  backend:
    build: ./backend
    container_name: cfh_backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/crochetfromheart
      - JWT_SECRET=your_jwt_secret_here
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_here
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=development
      - PORT=5000
      - STORAGE_PROVIDER=local
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: cfh_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongodb_data:
